### ISSUE TITLE
Transferring rows with cells that contain formulas resulting in a date, transfer the cell value from the template instead of the formula.

### ISSUE THREAD

**Issue by elyesAkkari1** [aVadim483/fast-excel-templator#10]
Working with Fast-Excel-Templator, I'm transferring rows from a sheet that mostly contains formulas. In order to use those formulas in my output file, for some cells that result in dates, instead of transferring the formula of the cell, it's transferring the hard value from the template file. (Issue only with dates)

Example:
Template file:
![image](https://github.com/aVadim483/fast-excel-templator/assets/147528161/c1e2139d-1baf-487f-8fe0-5ccc8ebd9421)

Output file:
![image](https://github.com/aVadim483/fast-excel-templator/assets/147528161/63789f76-5542-43b3-946a-0bb8b8593175)

Code snippet:

```
$spreadsheet = Excel::template($templatePath);
$sheetNames = $spreadsheet->getSheetNames();
foreach ($sheetNames as $sheetName) {
$sheet = $spreadsheet->getSheet($sheetName);
if (false === str_starts_with($sheetName, 'FEC')) {
   $sheet->transferRows();
  }
}
```

**Comment by aVadim483** [comment]
fixed
