### ISSUE TITLE
Error updating

### ISSUE THREAD

**Issue by lollita** [aVadim483/fast-excel-templator#13]
```
$i=true;
$rowTemplate = $sheet->getRowTemplate(1);
foreach ($rows as $v){
if($i===true){
	$i=false;
	$sheet->replaceRow(2, $rowTemplate, $v);
}else{
	$sheet->insertRow($rowTemplate, $v);
}
}
```

> <b>Fatal error</b>:  Uncaught TypeError: avadim\FastExcelTemplator\Sheet::replaceRow(): Argument #2 ($cellData) must be of type ?array, avadim\FastExcelTemplator\RowTemplateCollection given, called in K:\test.php on line 1535 and defined in C:\vendor\avadim\fast-excel-templator\src\FastExcelTemplator\Sheet.php:387

Occour error when update to 2.1.1.
insertRow work but replaceRow not.
Do it have a guidelines to update?
I have updated, removing and reinstalling.

**Comment by lollita** [comment]
I changed to
```
$sheet->transferRowsUntil(1);
$rowTemplate = $sheet->getRowTemplate(1);
foreach ($rows as $v){
$sheet->insertRow($rowTemplate, $v);
}
```
It work, Do it is right?

**Comment by aVadim483** [comment]
Yes, version 2 uses a different principle. You take the template and wrap the lines into the target file. To do this, use the transferRows()/transferRowsUntil() or insertRow() functions. Lines are written to the target file one after another, so there is no need to specify the line number in the target file.

See example here: https://github.com/aVadim483/fast-excel-templator/blob/main/README.md
