### ISSUE TITLE
When templating xlsx some data is removed

### ISSUE THREAD

**Issue by Raman117** [aVadim483/fast-excel-templator#6]
I see that you have added version 2
Question:
1. have you added anything for running formulas at the end.
2. can we add images now? from template to sheet 3 of A12
3. also now the formulas don't run even if we calculate them in excel

**Comment by Raman117** [comment]
nvm i used version 2 and was able to fix this issue
Qwestion:
1. have you added anything for running formulas at the end
2. can we add images now? from template to sheet 3 of A12

**Comment by aVadim483** [comment]
1. No, unfortunately, it is impossible to calculate the result using the formula, so this will not happen.
2. Not yet, but there are plans
3. This behavior is strange, maybe some bug, I need a real example to test.

**Comment by Raman117** [comment]
an example is

![image](https://github.com/aVadim483/fast-excel-templator/assets/105584135/89bd34f8-2689-4dcf-aa2a-6717c9f466e7)

here in the green where its implemented, lets say i added some text then
the text above in headers between those 2 rows
will just be blank

the data doesn't change in the place where it should the the row between is just blank

it was working in v1
but not in v2

**Comment by aVadim483** [comment]
Oh no, version 1 is no longer supported. It had many shortcomings, so the code was refactored and version 2 was released
